# Generated by Django 5.2.17 on 2026-10-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('vehiclenumber', models.CharField(max_length=100)),
                ('vehiclenmodel', models.CharField(max_length=100)),
                ('vehiclentype', models.CharField(max_length=50)),
            ],
        ),
    ]
