# Generated by Django 5.2.17 on 2026-10-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='vehiclenmodel',
            new_name='vehicle_model',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='vehiclentype',
            new_name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vehiclenumber',
        ),
        migrations.AddField(
            model_name='customer',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
