# Generated by Django 5.2.17 on 2026-10-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_vehiclenmodel_customer_vehicle_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
    ]
