# Generated by Django 5.2.17 on 2026-10-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
