# Generated by Django 5.2.17 on 2026-10-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SparePart',
        ),
    ]
