# Generated by Django 5.2.17 on 2026-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_delete_sparepart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='customer',
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Service', 'In Service'), ('Completed', 'Completed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
