# Generated by Django 5.2.17 on 2026-10-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_remove_customer_user'),
        ('Service', '0003_remove_servicebooking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='customer',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='Accounts.customer'),
            preserve_default=False,
        ),
    ]
